<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatCertificadoNacimiento', 'doctrine');

/**
 * BaseDatCertificadoNacimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nro_certificado
 * @property string $oficialia
 * @property string $libro
 * @property string $partida
 * @property string $folio
 * 
 * @method integer                  getNroCertificado()  Returns the current record's "nro_certificado" value
 * @method string                   getOficialia()       Returns the current record's "oficialia" value
 * @method string                   getLibro()           Returns the current record's "libro" value
 * @method string                   getPartida()         Returns the current record's "partida" value
 * @method string                   getFolio()           Returns the current record's "folio" value
 * @method DatCertificadoNacimiento setNroCertificado()  Sets the current record's "nro_certificado" value
 * @method DatCertificadoNacimiento setOficialia()       Sets the current record's "oficialia" value
 * @method DatCertificadoNacimiento setLibro()           Sets the current record's "libro" value
 * @method DatCertificadoNacimiento setPartida()         Sets the current record's "partida" value
 * @method DatCertificadoNacimiento setFolio()           Sets the current record's "folio" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDatCertificadoNacimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_certificado_nacimiento');
        $this->hasColumn('nro_certificado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('oficialia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('libro', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('partida', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('folio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}