<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UniSedeCarreraGestion', 'doctrine');

/**
 * BaseUniSedeCarreraGestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uni_sede_id
 * @property integer $uni_carrera_id
 * @property integer $gestion_id
 * @property ClaGestionSemestre $ClaGestionSemestre
 * 
 * @method integer               getUniSedeId()          Returns the current record's "uni_sede_id" value
 * @method integer               getUniCarreraId()       Returns the current record's "uni_carrera_id" value
 * @method integer               getGestionId()          Returns the current record's "gestion_id" value
 * @method ClaGestionSemestre    getClaGestionSemestre() Returns the current record's "ClaGestionSemestre" value
 * @method UniSedeCarreraGestion setUniSedeId()          Sets the current record's "uni_sede_id" value
 * @method UniSedeCarreraGestion setUniCarreraId()       Sets the current record's "uni_carrera_id" value
 * @method UniSedeCarreraGestion setGestionId()          Sets the current record's "gestion_id" value
 * @method UniSedeCarreraGestion setClaGestionSemestre() Sets the current record's "ClaGestionSemestre" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUniSedeCarreraGestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uni_sede_carrera_gestion');
        $this->hasColumn('uni_sede_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('uni_carrera_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('gestion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGestionSemestre', array(
             'local' => 'gestion_id',
             'foreign' => 'id'));
    }
}