<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaTramite', 'doctrine');

/**
 * BaseClaTramite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property string $nro_resolucion
 * @property timestamp $fecha_resolucion
 * @property Doctrine_Collection $ClaProceso
 * @property Doctrine_Collection $RelRolesTramite
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getDescripcion()      Returns the current record's "descripcion" value
 * @method string              getNroResolucion()    Returns the current record's "nro_resolucion" value
 * @method timestamp           getFechaResolucion()  Returns the current record's "fecha_resolucion" value
 * @method Doctrine_Collection getClaProceso()       Returns the current record's "ClaProceso" collection
 * @method Doctrine_Collection getRelRolesTramite()  Returns the current record's "RelRolesTramite" collection
 * @method ClaTramite          setId()               Sets the current record's "id" value
 * @method ClaTramite          setDescripcion()      Sets the current record's "descripcion" value
 * @method ClaTramite          setNroResolucion()    Sets the current record's "nro_resolucion" value
 * @method ClaTramite          setFechaResolucion()  Sets the current record's "fecha_resolucion" value
 * @method ClaTramite          setClaProceso()       Sets the current record's "ClaProceso" collection
 * @method ClaTramite          setRelRolesTramite()  Sets the current record's "RelRolesTramite" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaTramite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_tramite');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'cla_tramite_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nro_resolucion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_resolucion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaProceso', array(
             'local' => 'id',
             'foreign' => 'cla_tramite_id'));

        $this->hasMany('RelRolesTramite', array(
             'local' => 'id',
             'foreign' => 'tramite_id'));
    }
}