<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaHabilitado', 'doctrine');

/**
 * BaseClaHabilitado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $AdmRolesMenus
 * @property Doctrine_Collection $AdmUsuarios
 * @property Doctrine_Collection $AdmMenus
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method Doctrine_Collection getAdmRolesMenus() Returns the current record's "AdmRolesMenus" collection
 * @method Doctrine_Collection getAdmUsuarios()   Returns the current record's "AdmUsuarios" collection
 * @method Doctrine_Collection getAdmMenus()      Returns the current record's "AdmMenus" collection
 * @method ClaHabilitado       setId()            Sets the current record's "id" value
 * @method ClaHabilitado       setDescripcion()   Sets the current record's "descripcion" value
 * @method ClaHabilitado       setAdmRolesMenus() Sets the current record's "AdmRolesMenus" collection
 * @method ClaHabilitado       setAdmUsuarios()   Sets the current record's "AdmUsuarios" collection
 * @method ClaHabilitado       setAdmMenus()      Sets the current record's "AdmMenus" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaHabilitado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_habilitado');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdmRolesMenus', array(
             'local' => 'id',
             'foreign' => 'habilitado'));

        $this->hasMany('AdmUsuarios', array(
             'local' => 'id',
             'foreign' => 'habilitado'));

        $this->hasMany('AdmMenus', array(
             'local' => 'id',
             'foreign' => 'habilitado'));
    }
}