<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmMenus', 'doctrine');

/**
 * BaseAdmMenus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property string $abreviatura
 * @property boolean $estado
 * @property string $link
 * @property integer $tipo_menu
 * @property integer $orden
 * @property integer $adm_menu_id
 * @property string $icon
 * @property Doctrine_Collection $AdmMenus
 * @property Doctrine_Collection $AdmRolesMenus
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method string              getAbreviatura()   Returns the current record's "abreviatura" value
 * @method boolean             getEstado()        Returns the current record's "estado" value
 * @method string              getLink()          Returns the current record's "link" value
 * @method integer             getTipoMenu()      Returns the current record's "tipo_menu" value
 * @method integer             getOrden()         Returns the current record's "orden" value
 * @method integer             getAdmMenuId()     Returns the current record's "adm_menu_id" value
 * @method string              getIcon()          Returns the current record's "icon" value
 * @method Doctrine_Collection getAdmMenus()      Returns the current record's "AdmMenus" collection
 * @method Doctrine_Collection getAdmRolesMenus() Returns the current record's "AdmRolesMenus" collection
 * @method AdmMenus            setId()            Sets the current record's "id" value
 * @method AdmMenus            setDescripcion()   Sets the current record's "descripcion" value
 * @method AdmMenus            setAbreviatura()   Sets the current record's "abreviatura" value
 * @method AdmMenus            setEstado()        Sets the current record's "estado" value
 * @method AdmMenus            setLink()          Sets the current record's "link" value
 * @method AdmMenus            setTipoMenu()      Sets the current record's "tipo_menu" value
 * @method AdmMenus            setOrden()         Sets the current record's "orden" value
 * @method AdmMenus            setAdmMenuId()     Sets the current record's "adm_menu_id" value
 * @method AdmMenus            setIcon()          Sets the current record's "icon" value
 * @method AdmMenus            setAdmMenus()      Sets the current record's "AdmMenus" collection
 * @method AdmMenus            setAdmRolesMenus() Sets the current record's "AdmRolesMenus" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmMenus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_menus');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'adm_menus_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('abreviatura', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('link', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_menu', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('orden', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('adm_menu_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('icon', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdmMenus', array(
             'local' => 'id',
             'foreign' => 'adm_menu_id'));

        $this->hasMany('AdmRolesMenus', array(
             'local' => 'id',
             'foreign' => 'adm_menu_id'));
    }
}