<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaGeografico', 'doctrine');

/**
 * BaseClaGeografico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo_ine
 * @property integer $tipo_id
 * @property string $descripcion
 * @property integer $cla_geografico_id
 * @property Doctrine_Collection $ClaGeografico
 * @property Doctrine_Collection $DatCertificadoNacimiento
 * @property Doctrine_Collection $DatCertificadoNacimiento_2
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method string              getCodigoIne()                  Returns the current record's "codigo_ine" value
 * @method integer             getTipoId()                     Returns the current record's "tipo_id" value
 * @method string              getDescripcion()                Returns the current record's "descripcion" value
 * @method integer             getClaGeograficoId()            Returns the current record's "cla_geografico_id" value
 * @method Doctrine_Collection getClaGeografico()              Returns the current record's "ClaGeografico" collection
 * @method Doctrine_Collection getDatCertificadoNacimiento()   Returns the current record's "DatCertificadoNacimiento" collection
 * @method Doctrine_Collection getDatCertificadoNacimiento2()  Returns the current record's "DatCertificadoNacimiento_2" collection
 * @method ClaGeografico       setId()                         Sets the current record's "id" value
 * @method ClaGeografico       setCodigoIne()                  Sets the current record's "codigo_ine" value
 * @method ClaGeografico       setTipoId()                     Sets the current record's "tipo_id" value
 * @method ClaGeografico       setDescripcion()                Sets the current record's "descripcion" value
 * @method ClaGeografico       setClaGeograficoId()            Sets the current record's "cla_geografico_id" value
 * @method ClaGeografico       setClaGeografico()              Sets the current record's "ClaGeografico" collection
 * @method ClaGeografico       setDatCertificadoNacimiento()   Sets the current record's "DatCertificadoNacimiento" collection
 * @method ClaGeografico       setDatCertificadoNacimiento2()  Sets the current record's "DatCertificadoNacimiento_2" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaGeografico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_geografico');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'cla_geografico_id',
             'length' => 4,
             ));
        $this->hasColumn('codigo_ine', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cla_geografico_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'sequence' => 'cla_geografico_cla_geografico_id',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaGeografico', array(
             'local' => 'id',
             'foreign' => 'cla_geografico_id'));

        $this->hasMany('DatCertificadoNacimiento', array(
             'local' => 'id',
             'foreign' => 'departamento_id'));

        $this->hasMany('DatCertificadoNacimiento as DatCertificadoNacimiento_2', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));
    }
}