<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UniUniversidad', 'doctrine');

/**
 * BaseUniUniversidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $UniSede
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getUniSede()     Returns the current record's "UniSede" collection
 * @method UniUniversidad      setId()          Sets the current record's "id" value
 * @method UniUniversidad      setDescripcion() Sets the current record's "descripcion" value
 * @method UniUniversidad      setUniSede()     Sets the current record's "UniSede" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUniUniversidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uni_universidad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UniSede', array(
             'local' => 'id',
             'foreign' => 'uni_universidad_id'));
    }
}