<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaGestionSemestre', 'doctrine');

/**
 * BaseClaGestionSemestre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $semestre
 * @property integer $anio
 * @property Doctrine_Collection $UniSedeCarreraGestion
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getCodigo()                Returns the current record's "codigo" value
 * @method string              getSemestre()              Returns the current record's "semestre" value
 * @method integer             getAnio()                  Returns the current record's "anio" value
 * @method Doctrine_Collection getUniSedeCarreraGestion() Returns the current record's "UniSedeCarreraGestion" collection
 * @method ClaGestionSemestre  setId()                    Sets the current record's "id" value
 * @method ClaGestionSemestre  setCodigo()                Sets the current record's "codigo" value
 * @method ClaGestionSemestre  setSemestre()              Sets the current record's "semestre" value
 * @method ClaGestionSemestre  setAnio()                  Sets the current record's "anio" value
 * @method ClaGestionSemestre  setUniSedeCarreraGestion() Sets the current record's "UniSedeCarreraGestion" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaGestionSemestre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_gestion_semestre');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('semestre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('anio', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UniSedeCarreraGestion', array(
             'local' => 'id',
             'foreign' => 'gestion_id'));
    }
}