<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaRuta', 'doctrine');

/**
 * BaseClaRuta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $origen_id
 * @property integer $destino_id
 * @property integer $cla_tramite_id
 * 
 * @method integer getOrigenId()       Returns the current record's "origen_id" value
 * @method integer getDestinoId()      Returns the current record's "destino_id" value
 * @method integer getClaTramiteId()   Returns the current record's "cla_tramite_id" value
 * @method ClaRuta setOrigenId()       Sets the current record's "origen_id" value
 * @method ClaRuta setDestinoId()      Sets the current record's "destino_id" value
 * @method ClaRuta setClaTramiteId()   Sets the current record's "cla_tramite_id" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaRuta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_ruta');
        $this->hasColumn('origen_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('destino_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('cla_tramite_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}