<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaFormulario', 'doctrine');

/**
 * BaseClaFormulario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property string $url
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method string        getDescripcion() Returns the current record's "descripcion" value
 * @method string        getUrl()         Returns the current record's "url" value
 * @method ClaFormulario setId()          Sets the current record's "id" value
 * @method ClaFormulario setDescripcion() Sets the current record's "descripcion" value
 * @method ClaFormulario setUrl()         Sets the current record's "url" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaFormulario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_formulario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'cla_formulario_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}