<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UniSedeCarreras', 'doctrine');

/**
 * BaseUniSedeCarreras
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uni_sede_id
 * @property integer $uni_carrera_id
 * @property string $resolucion
 * @property timestamp $fecha_inicio
 * @property integer $duracion
 * @property integer $cla_grado_academico_id
 * @property ClaGradoAcademico $ClaGradoAcademico
 * @property UniCarreras $UniCarreras
 * @property UniSede $UniSede
 * 
 * @method integer           getUniSedeId()              Returns the current record's "uni_sede_id" value
 * @method integer           getUniCarreraId()           Returns the current record's "uni_carrera_id" value
 * @method string            getResolucion()             Returns the current record's "resolucion" value
 * @method timestamp         getFechaInicio()            Returns the current record's "fecha_inicio" value
 * @method integer           getDuracion()               Returns the current record's "duracion" value
 * @method integer           getClaGradoAcademicoId()    Returns the current record's "cla_grado_academico_id" value
 * @method ClaGradoAcademico getClaGradoAcademico()      Returns the current record's "ClaGradoAcademico" value
 * @method UniCarreras       getUniCarreras()            Returns the current record's "UniCarreras" value
 * @method UniSede           getUniSede()                Returns the current record's "UniSede" value
 * @method UniSedeCarreras   setUniSedeId()              Sets the current record's "uni_sede_id" value
 * @method UniSedeCarreras   setUniCarreraId()           Sets the current record's "uni_carrera_id" value
 * @method UniSedeCarreras   setResolucion()             Sets the current record's "resolucion" value
 * @method UniSedeCarreras   setFechaInicio()            Sets the current record's "fecha_inicio" value
 * @method UniSedeCarreras   setDuracion()               Sets the current record's "duracion" value
 * @method UniSedeCarreras   setClaGradoAcademicoId()    Sets the current record's "cla_grado_academico_id" value
 * @method UniSedeCarreras   setClaGradoAcademico()      Sets the current record's "ClaGradoAcademico" value
 * @method UniSedeCarreras   setUniCarreras()            Sets the current record's "UniCarreras" value
 * @method UniSedeCarreras   setUniSede()                Sets the current record's "UniSede" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUniSedeCarreras extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uni_sede_carreras');
        $this->hasColumn('uni_sede_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('uni_carrera_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('resolucion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('duracion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cla_grado_academico_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGradoAcademico', array(
             'local' => 'cla_grado_academico_id',
             'foreign' => 'id'));

        $this->hasOne('UniCarreras', array(
             'local' => 'uni_carrera_id',
             'foreign' => 'id'));

        $this->hasOne('UniSede', array(
             'local' => 'uni_sede_id',
             'foreign' => 'id'));
    }
}