<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatDiploma', 'doctrine');

/**
 * BaseDatDiploma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dat_institucion_id
 * @property integer $nro
 * @property string $serie
 * @property timestamp $fecha_emision
 * @property integer $cla_grado_academico_id
 * @property integer $dat_persona_id
 * @property ClaGradoAcademico $ClaGradoAcademico
 * @property DatInstitucion $DatInstitucion
 * @property DatPersonas $DatPersonas
 * 
 * @method integer           getId()                     Returns the current record's "id" value
 * @method integer           getDatInstitucionId()       Returns the current record's "dat_institucion_id" value
 * @method integer           getNro()                    Returns the current record's "nro" value
 * @method string            getSerie()                  Returns the current record's "serie" value
 * @method timestamp         getFechaEmision()           Returns the current record's "fecha_emision" value
 * @method integer           getClaGradoAcademicoId()    Returns the current record's "cla_grado_academico_id" value
 * @method integer           getDatPersonaId()           Returns the current record's "dat_persona_id" value
 * @method ClaGradoAcademico getClaGradoAcademico()      Returns the current record's "ClaGradoAcademico" value
 * @method DatInstitucion    getDatInstitucion()         Returns the current record's "DatInstitucion" value
 * @method DatPersonas       getDatPersonas()            Returns the current record's "DatPersonas" value
 * @method DatDiploma        setId()                     Sets the current record's "id" value
 * @method DatDiploma        setDatInstitucionId()       Sets the current record's "dat_institucion_id" value
 * @method DatDiploma        setNro()                    Sets the current record's "nro" value
 * @method DatDiploma        setSerie()                  Sets the current record's "serie" value
 * @method DatDiploma        setFechaEmision()           Sets the current record's "fecha_emision" value
 * @method DatDiploma        setClaGradoAcademicoId()    Sets the current record's "cla_grado_academico_id" value
 * @method DatDiploma        setDatPersonaId()           Sets the current record's "dat_persona_id" value
 * @method DatDiploma        setClaGradoAcademico()      Sets the current record's "ClaGradoAcademico" value
 * @method DatDiploma        setDatInstitucion()         Sets the current record's "DatInstitucion" value
 * @method DatDiploma        setDatPersonas()            Sets the current record's "DatPersonas" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDatDiploma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_diploma');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('dat_institucion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('nro', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('serie', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_emision', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('cla_grado_academico_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('dat_persona_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGradoAcademico', array(
             'local' => 'cla_grado_academico_id',
             'foreign' => 'id'));

        $this->hasOne('DatInstitucion', array(
             'local' => 'dat_institucion_id',
             'foreign' => 'id'));

        $this->hasOne('DatPersonas', array(
             'local' => 'dat_persona_id',
             'foreign' => 'id'));
    }
}