<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaCargo', 'doctrine');

/**
 * BaseClaCargo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $AdmUsuarioAdministra
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getDescripcion()          Returns the current record's "descripcion" value
 * @method Doctrine_Collection getAdmUsuarioAdministra() Returns the current record's "AdmUsuarioAdministra" collection
 * @method ClaCargo            setId()                   Sets the current record's "id" value
 * @method ClaCargo            setDescripcion()          Sets the current record's "descripcion" value
 * @method ClaCargo            setAdmUsuarioAdministra() Sets the current record's "AdmUsuarioAdministra" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaCargo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_cargo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'cla_cargo_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdmUsuarioAdministra', array(
             'local' => 'id',
             'foreign' => 'cla_cargo_id'));
    }
}