<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProcFormularios', 'doctrine');

/**
 * BaseProcFormularios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $gestion_id
 * @property integer $cla_tramite_id
 * @property integer $cla_proceso_id
 * @property integer $cla_formulario_id
 * @property integer $cla_tabla_id
 * @property integer $getid
 * @property ClaTabla $ClaTabla
 * 
 * @method integer         getId()                Returns the current record's "id" value
 * @method integer         getGestionId()         Returns the current record's "gestion_id" value
 * @method integer         getClaTramiteId()      Returns the current record's "cla_tramite_id" value
 * @method integer         getClaProcesoId()      Returns the current record's "cla_proceso_id" value
 * @method integer         getClaFormularioId()   Returns the current record's "cla_formulario_id" value
 * @method integer         getClaTablaId()        Returns the current record's "cla_tabla_id" value
 * @method integer         getGetid()             Returns the current record's "getid" value
 * @method ClaTabla        getClaTabla()          Returns the current record's "ClaTabla" value
 * @method ProcFormularios setId()                Sets the current record's "id" value
 * @method ProcFormularios setGestionId()         Sets the current record's "gestion_id" value
 * @method ProcFormularios setClaTramiteId()      Sets the current record's "cla_tramite_id" value
 * @method ProcFormularios setClaProcesoId()      Sets the current record's "cla_proceso_id" value
 * @method ProcFormularios setClaFormularioId()   Sets the current record's "cla_formulario_id" value
 * @method ProcFormularios setClaTablaId()        Sets the current record's "cla_tabla_id" value
 * @method ProcFormularios setGetid()             Sets the current record's "getid" value
 * @method ProcFormularios setClaTabla()          Sets the current record's "ClaTabla" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProcFormularios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proc_formularios');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('cla_tramite_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cla_proceso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cla_formulario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cla_tabla_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('getid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaTabla', array(
             'local' => 'cla_tabla_id',
             'foreign' => 'id'));
    }
}