<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaProceso', 'doctrine');

/**
 * BaseClaProceso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $nro_proceso
 * @property integer $cla_tramite_id
 * @property string $descripcion
 * @property integer $tiempo
 * @property integer $cla_tipo_proceso_id
 * @property ClaTipoProceso $ClaTipoProceso
 * @property ClaTramite $ClaTramite
 * 
 * @method integer        getId()                  Returns the current record's "id" value
 * @method integer        getNroProceso()          Returns the current record's "nro_proceso" value
 * @method integer        getClaTramiteId()        Returns the current record's "cla_tramite_id" value
 * @method string         getDescripcion()         Returns the current record's "descripcion" value
 * @method integer        getTiempo()              Returns the current record's "tiempo" value
 * @method integer        getClaTipoProcesoId()    Returns the current record's "cla_tipo_proceso_id" value
 * @method ClaTipoProceso getClaTipoProceso()      Returns the current record's "ClaTipoProceso" value
 * @method ClaTramite     getClaTramite()          Returns the current record's "ClaTramite" value
 * @method ClaProceso     setId()                  Sets the current record's "id" value
 * @method ClaProceso     setNroProceso()          Sets the current record's "nro_proceso" value
 * @method ClaProceso     setClaTramiteId()        Sets the current record's "cla_tramite_id" value
 * @method ClaProceso     setDescripcion()         Sets the current record's "descripcion" value
 * @method ClaProceso     setTiempo()              Sets the current record's "tiempo" value
 * @method ClaProceso     setClaTipoProcesoId()    Sets the current record's "cla_tipo_proceso_id" value
 * @method ClaProceso     setClaTipoProceso()      Sets the current record's "ClaTipoProceso" value
 * @method ClaProceso     setClaTramite()          Sets the current record's "ClaTramite" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaProceso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_proceso');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'cla_proceso_id',
             'length' => 4,
             ));
        $this->hasColumn('nro_proceso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cla_tramite_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tiempo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cla_tipo_proceso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaTipoProceso', array(
             'local' => 'cla_tipo_proceso_id',
             'foreign' => 'id'));

        $this->hasOne('ClaTramite', array(
             'local' => 'cla_tramite_id',
             'foreign' => 'id'));
    }
}