<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaTabla', 'doctrine');

/**
 * BaseClaTabla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $ProcFormularios
 * @property Doctrine_Collection $ClaFormulario
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getDescripcion()     Returns the current record's "descripcion" value
 * @method Doctrine_Collection getProcFormularios() Returns the current record's "ProcFormularios" collection
 * @method Doctrine_Collection getClaFormulario()   Returns the current record's "ClaFormulario" collection
 * @method ClaTabla            setId()              Sets the current record's "id" value
 * @method ClaTabla            setDescripcion()     Sets the current record's "descripcion" value
 * @method ClaTabla            setProcFormularios() Sets the current record's "ProcFormularios" collection
 * @method ClaTabla            setClaFormulario()   Sets the current record's "ClaFormulario" collection
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaTabla extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_tabla');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'cla_tabla_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProcFormularios', array(
             'local' => 'id',
             'foreign' => 'cla_tabla_id'));

        $this->hasMany('ClaFormulario', array(
             'local' => 'id',
             'foreign' => 'cla_tabla_id'));
    }
}