<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RelRolesTramite', 'doctrine');

/**
 * BaseRelRolesTramite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $adm_rol_id
 * @property integer $tramite_id
 * @property boolean $habilitado
 * @property AdmRoles $AdmRoles
 * @property ClaTramite $ClaTramite
 * 
 * @method integer         getAdmRolId()   Returns the current record's "adm_rol_id" value
 * @method integer         getTramiteId()  Returns the current record's "tramite_id" value
 * @method boolean         getHabilitado() Returns the current record's "habilitado" value
 * @method AdmRoles        getAdmRoles()   Returns the current record's "AdmRoles" value
 * @method ClaTramite      getClaTramite() Returns the current record's "ClaTramite" value
 * @method RelRolesTramite setAdmRolId()   Sets the current record's "adm_rol_id" value
 * @method RelRolesTramite setTramiteId()  Sets the current record's "tramite_id" value
 * @method RelRolesTramite setHabilitado() Sets the current record's "habilitado" value
 * @method RelRolesTramite setAdmRoles()   Sets the current record's "AdmRoles" value
 * @method RelRolesTramite setClaTramite() Sets the current record's "ClaTramite" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelRolesTramite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rel_roles_tramite');
        $this->hasColumn('adm_rol_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('tramite_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('habilitado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdmRoles', array(
             'local' => 'adm_rol_id',
             'foreign' => 'id'));

        $this->hasOne('ClaTramite', array(
             'local' => 'tramite_id',
             'foreign' => 'id'));
    }
}