<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatHabilitacion', 'doctrine');

/**
 * BaseDatHabilitacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dat_persona_id
 * @property integer $uni_sede_id
 * @property integer $uni_carrera_id
 * @property integer $uni_gestion_id
 * @property integer $cla_grado_academico_id
 * @property integer $adm_usuario_id
 * @property timestamp $fecha_registro
 * @property AdmUsuarios $AdmUsuarios
 * @property ClaGradoAcademico $ClaGradoAcademico
 * @property DatPersonas $DatPersonas
 * @property UniSede $UniSede
 * 
 * @method integer           getId()                     Returns the current record's "id" value
 * @method integer           getDatPersonaId()           Returns the current record's "dat_persona_id" value
 * @method integer           getUniSedeId()              Returns the current record's "uni_sede_id" value
 * @method integer           getUniCarreraId()           Returns the current record's "uni_carrera_id" value
 * @method integer           getUniGestionId()           Returns the current record's "uni_gestion_id" value
 * @method integer           getClaGradoAcademicoId()    Returns the current record's "cla_grado_academico_id" value
 * @method integer           getAdmUsuarioId()           Returns the current record's "adm_usuario_id" value
 * @method timestamp         getFechaRegistro()          Returns the current record's "fecha_registro" value
 * @method AdmUsuarios       getAdmUsuarios()            Returns the current record's "AdmUsuarios" value
 * @method ClaGradoAcademico getClaGradoAcademico()      Returns the current record's "ClaGradoAcademico" value
 * @method DatPersonas       getDatPersonas()            Returns the current record's "DatPersonas" value
 * @method UniSede           getUniSede()                Returns the current record's "UniSede" value
 * @method DatHabilitacion   setId()                     Sets the current record's "id" value
 * @method DatHabilitacion   setDatPersonaId()           Sets the current record's "dat_persona_id" value
 * @method DatHabilitacion   setUniSedeId()              Sets the current record's "uni_sede_id" value
 * @method DatHabilitacion   setUniCarreraId()           Sets the current record's "uni_carrera_id" value
 * @method DatHabilitacion   setUniGestionId()           Sets the current record's "uni_gestion_id" value
 * @method DatHabilitacion   setClaGradoAcademicoId()    Sets the current record's "cla_grado_academico_id" value
 * @method DatHabilitacion   setAdmUsuarioId()           Sets the current record's "adm_usuario_id" value
 * @method DatHabilitacion   setFechaRegistro()          Sets the current record's "fecha_registro" value
 * @method DatHabilitacion   setAdmUsuarios()            Sets the current record's "AdmUsuarios" value
 * @method DatHabilitacion   setClaGradoAcademico()      Sets the current record's "ClaGradoAcademico" value
 * @method DatHabilitacion   setDatPersonas()            Sets the current record's "DatPersonas" value
 * @method DatHabilitacion   setUniSede()                Sets the current record's "UniSede" value
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDatHabilitacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_habilitacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'dat_habilitacion_id',
             'length' => 4,
             ));
        $this->hasColumn('dat_persona_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('uni_sede_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('uni_carrera_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('uni_gestion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cla_grado_academico_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('adm_usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_registro', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdmUsuarios', array(
             'local' => 'adm_usuario_id',
             'foreign' => 'id'));

        $this->hasOne('ClaGradoAcademico', array(
             'local' => 'cla_grado_academico_id',
             'foreign' => 'id'));

        $this->hasOne('DatPersonas', array(
             'local' => 'dat_persona_id',
             'foreign' => 'id'));

        $this->hasOne('UniSede', array(
             'local' => 'uni_sede_id',
             'foreign' => 'id'));
    }
}