<?php

/**
 * AdmMenusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMenusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMenusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMenus');
    }
    
    public function getMenus($rol_id, $tipo)
    {
        $q = $this->createQuery('c')
        ->InnerJoin('c.AdmRolesMenus d')
        ->where('d.adm_rol_id = ?',$rol_id)
        ->andWhere('c.tipo_menu = ?',$tipo)
        ->andWhere('c.habilitado = ?',1)
        ->orderBy('c.orden ASC');
        return $q->execute();
    }
    
    public function getSubMenus($rol_id, $menu)
    {
        $q = $this->createQuery('c')
        ->InnerJoin('c.AdmRolesMenus d')
        ->where('d.adm_rol_id = ?',$rol_id)
        ->andWhere('c.tipo_menu = ?','1')
        ->andWhere('c.adm_menu_id = ?', $menu)
        ->andWhere('c.habilitado = ?',1)
        ->orderBy('c.orden ASC');
        return $q->execute();
    }
}