<?php

/**
 * AdmRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmRoles');
    }
}