<?php

/**
 * AdmRolesMenusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmRolesMenusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmRolesMenusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmRolesMenus');
    }
    
    
}