<?php

/**
 * AdmRolesUsuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdmRolesUsuarios extends BaseAdmRolesUsuarios
{

}