<?php

/**
 * AdmUsuarioAdministraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmUsuarioAdministraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmUsuarioAdministraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmUsuarioAdministra');
    }
}