<?php

/**
 * AdmUsuariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmUsuariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmUsuariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmUsuarios');
    }
    
    public function getListaUsuarios(){
        $q = $this->createQuery('c')
        ->innerJoin('c.AdmRoles g')        
        ->innerJoin('c.DatPersonas d');
        
        return $q;
    }
    
}