<?php

/**
 * ClaCargoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaCargoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaCargoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaCargo');
    }
}