<?php

/**
 * ClaDocumentosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaDocumentosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaDocumentosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaDocumentos');
    }
}