<?php

/**
 * ClaFormulario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaFormulario extends BaseClaFormulario
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaProcesoFormularios', array(
             'local' => 'id',
             'foreign' => 'cla_formulario_id'));
        
    }

}