<?php

/**
 * ClaGestionSemestreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaGestionSemestreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaGestionSemestreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaGestionSemestre');
    }
    
    public function getGestiones($sede, $carrera){
        $q = $this->createQuery('c')
            ->innerJoin('c.UniSedeCarreraGestion d')
            ->where('d.uni_sede_id = ?', $sede)
            ->andWhere('d.uni_carrera_id = ?', $carrera);
            return $q->execute();
    }
}