<?php

/**
 * ClaGeograficoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaGeograficoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaGeograficoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaGeografico');
    }
}