<?php

/**
 * ClaGestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaGestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaGestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaGestion');
    }
}