<?php

/**
 * ClaGestionSemestreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaGestionSemestreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaGestionSemestreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaGestionSemestre');
    }
}