<?php

/**
 * ClaHabilitadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaHabilitadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaHabilitadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaHabilitado');
    }
}