<?php

/**
 * ClaModalidadEgresoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaModalidadEgresoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaModalidadEgresoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaModalidadEgreso');
    }
}