<?php

/**
 * ClaProcesoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaProcesoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaProcesoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaProceso');
    }
    
    public function getProcesoInit($rol_id, $tramite_id)
    {
        $q = $this->createQuery('c')
        ->leftJoin('c.RelRolesProceso d')
        ->innerJoin('c.ClaTipoProceso e')
        ->where('d.adm_rol_id = ?',$rol_id)
        ->andWhere('d.tramite_id = ?',$tramite_id)
        ->andWhere('e.descripcion = ?','Init')
        ->andWhere('d.habilitado = ?','t');
        return $q->fetchOne();
    }
    
    public function isProcesoInit($tramite_id, $proceso_id)
    {
        $q = $this->createQuery('c')
        ->innerJoin('c.ClaTipoProceso d')
        ->where('c.cla_tramite_id = ?',$tramite_id)
        ->andWhere('c.id = ?',$proceso_id)
        ->andWhere('d.descripcion = ?','Init');
        $value = $q->fetchOne();
        if(empty($value)):
            return FALSE;
        else:
            return TRUE;
        endif;
        
    }
}