<?php

/**
 * ClaProceso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClaProceso extends BaseClaProceso
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RelRolesProceso', array(
             'local' => array('cla_tramite_id','id'),
             'foreign' => array('tramite_id','proceso_id')));
        
    }
}