<?php

/**
 * ClaTipoProcesoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaTipoProcesoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaTipoProcesoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaTipoProceso');
    }
}