<?php

/**
 * ClaTablaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaTablaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaTablaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaTabla');
    }
}