<?php

/**
 * ClaTramiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaTramiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaTramiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaTramite');
    }
    
    public function getTramites($rol_id)
    {
        $q = $this->createQuery('c')
        ->InnerJoin('c.RelRolesTramite d')
        ->where('d.adm_rol_id = ?',$rol_id)
        ->andWhere('d.habilitado = ?','t');
        return $q->execute();
    }
}