<?php

/**
 * DatCertificadoNacimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatCertificadoNacimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatCertificadoNacimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatCertificadoNacimiento');
    }
}