<?php

/**
 * DatDiplomaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatDiplomaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatDiplomaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatDiploma');
    }
}