<?php

/**
 * DatHabilitacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatHabilitacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatHabilitacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatHabilitacion');
    }
}