<?php

/**
 * DatInstitucionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatInstitucionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatInstitucionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatInstitucion');
    }
    
    public function getInstitucion($rol)
    {
        $q = $this->createQuery('c')
        ->innerJoin('c.AdmRoles d on c.id = d.dat_institucion_id')
        ->where('d.id = ?', $rol);
        return $q->fetchOne();
    }
}