<?php

/**
 * DatPersonasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatPersonasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatPersonasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatPersonas');
    }
}