<?php

/**
 * DatPersonas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DatPersonas extends BaseDatPersonas
{
    public function getNombreCompleto(){
        return $this->getNombre1().' '.$this->getNombre2().' '.$this->getPaterno().' '.$this->getMaterno();
    }
}