<?php

/**
 * ProcFormulariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProcFormulariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProcFormulariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProcFormularios');
    }
}