<?php

/**
 * ProcSeguimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProcSeguimiento extends BaseProcSeguimiento
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaProceso', array(
             'local' => array('cla_tramite_id','cla_proceso_id'),
             'foreign' => array('cla_tramite_id','id')));
        $this->hasMany('ProcFormularios', array(
             'local' => array('id','cla_tramite_id','cla_proceso_id'),
             'foreign' => array('id','cla_tramite_id','cla_proceso_id')));
        
    }
}