<?php

/**
 * RegInscripcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegInscripcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegInscripcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegInscripcion');
    }
}