<?php

/**
 * RelRolesTramiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelRolesTramiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelRolesTramiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelRolesTramite');
    }
}