<?php

/**
 * RelRolesProceso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    universidad
 * @subpackage model
 * @author     Remberto Quispe <rembertoy2k3@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RelRolesProceso extends BaseRelRolesProceso
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaProceso', array(
             'local' => array('tramite_id','proceso_id'),
             'foreign' => array('cla_tramite_id','id')));
        
        $this->hasOne('RelRolesTramite', array(
             'local' => array('adm_rol_id','tramite_id'),
             'foreign' => array('adm_rol_id','tramite_id')));
    }

}