<?php

/**
 * RelRolesProcesoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelRolesProcesoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelRolesProcesoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelRolesProceso');
    }
    
    
}