<?php

/**
 * UniCarrerasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniCarrerasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniCarrerasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniCarreras');
    }
}