<?php

/**
 * UniSedeCarreraGestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniSedeCarreraGestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniSedeCarreraGestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniSedeCarreraGestion');
    }
}