<?php

/**
 * UniSedeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniSedeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniSedeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniSede');
    }
    
    public function getSede($user_id)
    {
        $q = $this->createQuery('c')
        ->innerJoin('c.AdmUsuarioAdministra d')
        ->innerJoin('c.UniUniversidad e')
        ->where('d.adm_usuario_id = ?',$user_id);
        return $q->execute();
    }
}