<?php

/**
 * UniSedeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniSedeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniSedeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniSede');
    }
}