<?php

/**
 * UniSedeCarrerasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniSedeCarrerasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniSedeCarrerasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniSedeCarreras');
    }
}