<?php

/**
 * UniSedeCarrerasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniSedeCarrerasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniSedeCarrerasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniSedeCarreras');
    }
    
    public function getCarrera($sede, $carrera, $grado){
        $q = $this->createQuery('c')
        ->where('c.uni_sede_id = ?', $sede)
        ->andWhere('c.uni_carrera_id = ?', $carrera)
        ->andWhere('c.cla_grado_academico_id = ?', $grado);
        return $q->fetchOne();
    }
}