<?php

/**
 * UniUniversidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniUniversidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniUniversidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniUniversidad');
    }
}