<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/09 05:46:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=universidad',
  'username' => 'postgres',
  'password' => 'dinamica',
  'name' => 'doctrine',
)),);
