<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/18 06:12:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'postgres:host=localhost;dbname=universidad',
  'username' => 'postgres',
  'password' => 'postgresql',
  'name' => 'doctrine',
)),);
