<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/19 07:05:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=universidad',
  'username' => 'postgres',
  'password' => 'dinamica',
  'name' => 'doctrine',
)),);
